# avoid starting shell as login shell
set -g default-command /bin/zsh
#set -s escape-time 0
# Fix for WSL.
set -g escape-time 50

set -g base-index 1

# set prefix to `
unbind-key C-b
set-option -g prefix `
# press ` for 2 times to get `
bind ` send-prefix
# use ; for command prompt
unbind :
unbind \;
bind \; command-prompt

# screen like binding
unbind x
bind k confirm-before kill-pane

unbind [
bind Escape copy-mode

setw -g mode-keys vi
setw -g xterm-keys on
unbind %
bind _ split-window -v
bind | split-window -h
# update "terminal window" title
set-option -g set-titles on
# I rely on zsh to rename window title
setw -g automatic-rename off
set-option -g allow-rename on

set-option -g visual-activity on
setw -g monitor-activity on

# prevent application like less, vim clear screen after exit
set-window-option -g alternate-screen off
# Set to on because atuin need this.
#set-window-option -g alternate-screen on

#setw -g utf8 on
#set -g terminal-overrides "*88col*:colors=88,*256col*:colors=256,xterm*:colors=256"
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
#set -g default-terminal "xterm"
#set -g status-utf8 on
set -g status-justify centre

# Selenized Light 匹配配色
#set -g status-bg '#f0e9d7'       # 状态栏背景
#set -g status-fg '#474032'       # 状态栏默认文字色
## 左侧状态栏
#set -g status-left "#[fg=#d60000][ #[fg=#308000]#H #[fg=#d60000]]#[default]"
#set -g status-left-length 20
## 右侧状态栏
#set -g status-right-length 25
#set -g status-right "#[fg=#d60000][ #[fg=#308000]%H:%M #[fg=#b00080]%a %m-%d #[fg=#d60000]] #[default]"
## 普通窗口样式
#setw -g window-status-format '#[fg=#0066cc,bold]#I: #W#F#[default]'
## 当前激活窗口样式
#setw -g window-status-current-format '#[fg=#af8500,bold]#I: #W#F#[default] '

# Selenized Dark 配色
set -g status-bg '#252525'       # 状态栏背景
set -g status-fg '#f0e9d7'       # 状态栏文字主色
# 左侧状态栏（主机名）
set -g status-left "#[fg=#ff8080][ #[fg=#70c000]#H #[fg=#ff8080]]#[default]"
set -g status-left-length 20
# 右侧状态栏（时间 + 日期）
set -g status-right-length 25
set -g status-right "#[fg=#ff8080][ #[fg=#70c000]%H:%M #[fg=#d0a0f0]%a %m-%d #[fg=#ff8080]] #[default]"
# 普通窗口样式
setw -g window-status-format '#[fg=#60a0ff,bold]#I: #W#F#[default]'
# 当前激活窗口样式
setw -g window-status-current-format '#[fg=#ffcc00,bold]#I: #W#F#[default] '

# default window for session cmd
new-session -s cmd
new-window -d -t cmd:
new-window -d -t cmd:
new-window -d -t cmd:
new-window -d -t cmd:
